### ISSUE TITLE
[meta] Decrufting Master

### ISSUE THREAD

**Issue by bennypowers** [open-wc/open-wc#585]
At a recent meeting, @LarsDenBakker and @daKmoR noted the need to clean up the master and deprecate some packages. This meta-issue serves to document the work that needs to be done. @Westbrook and myself are good candidates to tackle these issues, to help us acquire context in the repo so we can proceed to help triage issues in the future.

Please edit the list as appropriate

- [x] Deprecate owc-dev-server in favour of es-dev-server
- [x] Rename all karma tests as `test:browser` and all node tests as `test:node`, in packages and in the root project.
- [ ] Unscope `@open-wc/webpack-plugin-index-html` to `webpack-plugin-index-html`
- [x] Deprecate `polyfills-loader`

**Comment by LarsDenBakker** [comment]
Added a bunch of tasks. @daKmoR turns out we can't deprecate the webpack import meta loader, as there are some cases that are not handled correctly by the babel import meta rewrite plugin.

**Comment by daKmoR** [comment]
sounds good 👍 

deprecation means
- release a new patch version with the upgrade path in the readme
- remove from repository

unscope means
- copy and rename everything => release 1.x version
- release a new patch version of the scoped package with upgrade path in the readme
- remove from repository

**Comment by LarsDenBakker** [comment]
Deprecating `owc-dev-server` with updated readme and a warning on install would be good to do pretty soon.

**Comment by noelmace** [comment]
Could you tell us what are the motivations for these depreciations and how do you plan to proceed? I can't find any information related to #687.

**Comment by daKmoR** [comment]
- es-dev-server is the next iteration of owc-dev-server and supersedes it in every way 
- an alternative approach to polyfills-loader has been fully integrated into building-utils and therefore is used in es-dev-server, building-rollup and building-webpack (if someone has a need of using this functionality way could consider extracting it into a separate package)

does this answer your question? or which kind of information are you looking for?

**Comment by noelmace** [comment]
Thx for this quick answer! It covers pretty much what I was looking for regarding these two packages.

I was especially concerned about chai-dom-equals being removed as it still was referenced in the docs. But then I saw that you added a deprecation to its README 4 months ago (https://github.com/open-wc/open-wc/blame/5e80a33f7f871a47ed94c98d32582e1523ee8c05/packages/chai-dom-equals/README.md#L5) referring to @open-wc/semantic-dom-diff which is pretty much identical.

So, I did a PR for that #702 :wink:
